//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMQuanLyKho.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMQuanLyKhoEntities : DbContext
    {
        public PMQuanLyKhoEntities()
            : base("name=PMQuanLyKhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<don_vi> don_vi { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<loai> loai { get; set; }
        public virtual DbSet<nguoi_dung> nguoi_dung { get; set; }
        public virtual DbSet<nha_cung_cap> nha_cung_cap { get; set; }
        public virtual DbSet<nhap_kho> nhap_kho { get; set; }
        public virtual DbSet<quyen_nguoi_dung> quyen_nguoi_dung { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vat_tu> vat_tu { get; set; }
        public virtual DbSet<xuat_Kho> xuat_Kho { get; set; }
    }
}
