//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMQuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_dung()
        {
            this.nhap_kho = new HashSet<nhap_kho>();
            this.xuat_Kho = new HashSet<xuat_Kho>();
        }
    
        public int id { get; set; }
        public string ten_nguoi_dung { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public int id_quyen { get; set; }
    
        public virtual quyen_nguoi_dung quyen_nguoi_dung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhap_kho> nhap_kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<xuat_Kho> xuat_Kho { get; set; }
    }
}
