//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMQuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vat_tu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vat_tu()
        {
            this.nhap_kho = new HashSet<nhap_kho>();
        }
    
        public string id { get; set; }
        public string ten_vat_tu { get; set; }
        public int id_don_vi { get; set; }
        public int id_nhacc { get; set; }
        public int id_loai { get; set; }
        public string QRCode { get; set; }
        public string BarCode { get; set; }
        public string mo_ta { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual don_vi don_vi { get; set; }
        public virtual loai loai { get; set; }
        public virtual nha_cung_cap nha_cung_cap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhap_kho> nhap_kho { get; set; }
    }
}
