//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMQuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xuat_Kho
    {
        public string id { get; set; }
        public int id_khach_hang { get; set; }
        public string id_hoadon { get; set; }
        public int id_nguoi_dung { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> ngay_xuat { get; set; }
        public string id_nhap_kho { get; set; }
        public string mo_ta { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual nhap_kho nhap_kho { get; set; }
    }
}
